---
- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes
  tasks:
    - name: Install dependencias
      ansible.builtin.apt:
        pkg:
        - apache2
        - ghostscript
        - libapache2-mod-php 
        - php 
        - php-bcmath 
        - php-curl 
        - php-imagick 
        - php-intl 
        - php-json 
        - php-mbstring 
        - php-mysql 
        - php-xml 
        - php-zip
        state: latest
        update_cache: yes
      become: yes
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /srv/www
        state: directory
        owner: www-data
        group: www-data
      become: yes
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /srv/www
        remote_src: yes
      become: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/wordpress.conf
        dest: /etc/apache2/sites-available/000-default.conf
      become: yes
      notify:
        - restart apache
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: '/srv/www/wordpress/wp-config-sample.php'
        dest: '/srv/www/wordpress/wp-config.php'
        force: no
        remote_src: yes
      become: yes
    - name: configure wp-config with database
      ansible.builtin.replace:
        path: '/srv/www/wordpress/wp-config.php'
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
      - { regexp: "database_name_here", replace: 'wordpress_db' }
      - { regexp: "username_here", replace: 'wordpress_user' }
      - { regexp: "password_here", replace: '12345'}
      - { regexp: "localhost", replace: '192.168.0.79'}
      become: yes
    - name: Replace a localhost entry searching for a literal string to avoid escaping
      ansible.builtin.lineinfile:
        path: /srv/www/wordpress/wp-config.php
        search_string: "{{ item.search_string }}"
        line: "{{ item.line }}"
      with_items:
      - { search_string: "define( 'AUTH_KEY',         'put your unique phrase here' );", line: "define('AUTH_KEY',         'Od?=2qPY Z(uP}{S$)izCRfsx}^Hl 2,!J)B/M}r x=?~B`&A`S,u&pI/$!.N!&^');" }
      - { search_string: "define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );", line: "define('SECURE_AUTH_KEY',  'wfO}^s @{xp0A)hU)[_qDX|cp;WLTW&EQ;=]? LPKxFV/Hpzg*Bc}TS! .^IV(}-');" }
      - { search_string: "define( 'LOGGED_IN_KEY',    'put your unique phrase here' );", line: "define('LOGGED_IN_KEY',    'I^rpD]2ke^<NvHc)y5g9EE^i+Z7j97|ZeEjdIG%/!l+3#JG#<I(q$4;:gEWN`YV ');" }
      - { search_string: "define( 'NONCE_KEY',        'put your unique phrase here' );", line: "define('NONCE_KEY',        'noP)<51OYM2~{M IL[Eps?V6&FzU5eN{_L:Ee3,q3QnB@c~Hc&J-;BqNU0#dq^6g');" }
      - { search_string: "define( 'AUTH_SALT',        'put your unique phrase here' );", line: "define('AUTH_SALT',        '9-QmI?|w&|a!IWn&|cDW|Y]r6`|VpRBo# Nu=%ORa{<- x5+5[`kzAFwA+-cfgQd');" }
      - { search_string: "define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );", line: "define('SECURE_AUTH_SALT', '*;|y(/4~bWv$I+$SjDk=udQ 0-L%<Tui#PnqE52]@>>ytdT#GLt6F,9O|f*%=b~-');" }
      - { search_string: "define( 'LOGGED_IN_SALT',   'put your unique phrase here' );", line: "define('LOGGED_IN_SALT',   'Tcd5SaACUQ5^+Ym-wm-~v|g+|Pml.0W+[[95tXdKhMDI&BIl@,il7[=Yj#8OL$Vi');" }
      - { search_string: "define( 'NONCE_SALT',       'put your unique phrase here' );", line: "define('NONCE_SALT',       '_!AY7+B0AY9ul$A-rP%+m4g<)N0b#(^RRs>r%sKvmr2)&Q4W$:2DSde 642X@C&c');" }
      become: yes

- hosts: mysql
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes
  tasks:
    - name: Install dependencias
      ansible.builtin.apt:
        pkg:
        - mysql-server
        - python3-pymysql
        state: latest
        update_cache: yes
      become: yes
    - name: Create a new database with name 'wordpress_db'
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes
    - name: Create database user with name 'wordpress_user' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        host: '{{ item }}'
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '192.168.0.239'
      become: yes
    - name: configure wp-config with database
      ansible.builtin.replace:
        path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
      become: yes
      notify:
        - restart mysql
